name: CD Gitops

on:
  push:
    branches: [main]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Bluid and push image to Dockerhub
      uses: docker/build-push-action@v1.1.0
      with:
        usernamer: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ secrets.DOCKER_USERNAME }}/gitopsfc
        tags: ${{ github.sha }}, latest
        